In [1]:
import numpy as np

In [8]:
#PART 1
matrix = np.random.rand(64,64)*255

In [9]:
matrix

array([[ 32.5906665 , 114.91170619, 146.34249374, ...,  26.58889914,
        213.2816447 ,  62.7802159 ],
       [ 14.39851431, 238.8397121 ,  20.18303371, ..., 202.78487637,
        230.77305505,  37.21476789],
       [222.97163809, 164.61578687,  19.3568619 , ..., 127.23985561,
        186.12179372, 130.8490923 ],
       ...,
       [ 76.81555707, 226.59898932,  35.82690809, ..., 145.90033947,
        245.90407816, 240.76549273],
       [218.98885132,   6.81855567,  51.42866225, ...,  43.06450083,
         66.22569682, 114.93441753],
       [ 49.76324264,  22.14688854, 128.23794993, ...,  74.09359391,
        135.64239837, 245.11052629]])

In [14]:
#PART 2
arr = np.hsplit(matrix,64)

In [16]:
arr

[array([[ 32.5906665 ],
        [ 14.39851431],
        [222.97163809],
        [ 58.47029912],
        [ 91.3945138 ],
        [154.18147956],
        [ 49.07856033],
        [  4.86238724],
        [128.58601997],
        [ 68.48573255],
        [134.72966277],
        [ 54.04702165],
        [101.67984349],
        [113.70630088],
        [191.00165877],
        [226.58421972],
        [221.58774287],
        [194.2566889 ],
        [201.65398607],
        [ 37.31903453],
        [139.07479365],
        [ 91.11423153],
        [204.68158098],
        [ 83.86182061],
        [ 90.88788023],
        [213.54022213],
        [146.75925467],
        [239.72689602],
        [145.59497539],
        [ 55.43885213],
        [104.10909137],
        [168.83970291],
        [ 85.19409585],
        [199.06690256],
        [ 96.42398883],
        [226.2342191 ],
        [161.31651838],
        [237.32713128],
        [105.62428057],
        [ 54.00615702],
        [145.83401276],
        [202.879

In [19]:
mean_col = np.mean(matrix, axis = 1)

In [20]:
mean_col

array([126.62040808, 144.66049066, 116.85142285, 117.06736472,
       115.03866185, 128.28495168, 126.58368691, 107.90022512,
       130.4736256 , 120.86531335, 133.05931582, 140.29202246,
       131.37496189, 129.12190022, 127.07620701, 121.7498858 ,
       142.52361508, 128.41246325, 118.54744299, 138.26456293,
       127.75761546, 120.14453012, 138.74037866, 117.32103165,
       117.22500135, 132.00506839, 126.04761278, 137.78043632,
       124.82504198, 123.63877393, 131.53824665,  99.11075313,
       122.3133518 , 117.33586832, 121.31071672, 132.75526055,
       130.56605192, 149.69689181, 129.46510774, 138.7836779 ,
       125.44056227, 137.53092564, 123.82384005, 126.18384832,
       118.92780908, 132.61482602, 129.02067604, 129.96912901,
       127.95707828, 123.79116467, 129.20254722, 132.73134968,
       128.21603042, 143.87087894, 125.92114261, 124.06588666,
       127.52549221, 112.02361539, 123.65358413, 128.81472271,
       134.3294319 , 121.98967385, 117.28022642, 129.19

In [21]:
std_col = np.std(matrix, axis = 1)

In [22]:
std_col

array([73.37198111, 74.84570143, 74.81188181, 72.39296642, 75.42817538,
       68.83951672, 64.11094576, 78.5529558 , 70.83184474, 74.39459434,
       71.98961183, 72.12670328, 72.18600534, 81.5611449 , 72.78440427,
       69.32534736, 70.68964713, 66.75804033, 75.73818444, 74.75666509,
       75.66801909, 73.29034178, 70.26841502, 73.64249759, 72.98923549,
       78.67367823, 73.36614639, 74.22548143, 77.4202853 , 77.24876972,
       73.4870843 , 73.22010029, 76.3826613 , 76.99734083, 75.45802416,
       72.04557789, 76.47342654, 68.39532887, 77.01876905, 70.65411269,
       63.9367431 , 79.15357726, 70.21627875, 66.670234  , 74.21573385,
       66.60587056, 72.47835012, 75.41376879, 68.86826754, 82.26183307,
       75.4568985 , 74.76866602, 74.4300538 , 77.26313774, 79.52495889,
       68.89213831, 73.90558194, 75.76700244, 72.80238877, 76.95453035,
       76.7654567 , 73.72612481, 66.39096698, 71.44253874])

In [23]:
mean_col2 = []
for i in range(64):
    sum = 0
    for j in range(64):
        sum=sum+arr[i][j]
    mean_col2.append(sum/64)
    
        
        

In [24]:
mean_col2

[array([133.06064468]),
 array([118.17206637]),
 array([124.99157874]),
 array([113.66245306]),
 array([119.13771782]),
 array([124.21166657]),
 array([134.09096441]),
 array([130.69025081]),
 array([127.6040371]),
 array([115.02756676]),
 array([127.64051711]),
 array([121.74560084]),
 array([130.12589967]),
 array([127.14094994]),
 array([119.53033852]),
 array([120.31363428]),
 array([122.78464033]),
 array([112.8190526]),
 array([128.36734793]),
 array([140.70799783]),
 array([141.92633358]),
 array([117.91950885]),
 array([129.0319397]),
 array([119.21066419]),
 array([130.22119856]),
 array([112.9520684]),
 array([118.72971577]),
 array([119.22172358]),
 array([129.74381821]),
 array([117.35956944]),
 array([135.34109102]),
 array([128.888944]),
 array([131.58269585]),
 array([134.84552019]),
 array([115.31682539]),
 array([124.99454473]),
 array([125.33131601]),
 array([138.67714575]),
 array([122.13245123]),
 array([132.48041659]),
 array([138.5037253]),
 array([126.04883957]),

In [28]:
var_col2 = []
for i in range(64):
    sum = 0
    for j in range(64):
        sum=sum+arr[i][j]
    mean = sum/64
    var_col2.append((((arr[i]-mean)**2)/64)**0.5)
    
    


In [29]:
var_col2

[array([[12.55874727],
        [14.8327663 ],
        [11.23887418],
        [ 9.32379319],
        [ 5.20826636],
        [ 2.64010436],
        [10.49776054],
        [16.02478218],
        [ 0.55932809],
        [ 8.07186402],
        [ 0.20862726],
        [ 9.87670288],
        [ 3.92260015],
        [ 2.41929297],
        [ 7.24262676],
        [11.69044688],
        [11.06588727],
        [ 7.64950553],
        [ 8.57416767],
        [11.96770127],
        [ 0.75176862],
        [ 5.24330164],
        [ 8.95261704],
        [ 6.14985301],
        [ 5.27159556],
        [10.05994718],
        [ 1.71232625],
        [13.33328142],
        [ 1.56679134],
        [ 9.70272407],
        [ 3.61894416],
        [ 4.47238228],
        [ 5.9833186 ],
        [ 8.25078223],
        [ 4.57958198],
        [11.6466968 ],
        [ 3.53198421],
        [13.03331082],
        [ 3.42954551],
        [ 9.88181096],
        [ 1.59667101],
        [ 8.72732633],
        [ 1.60510285],
        [ 4